[tools]
actionlint = "latest"
"github:editorconfig-checker/editorconfig-checker" = "latest"
gitleaks = "latest"
glab = "latest"
hadolint = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
